# Generated by Django 3.1.6 on 2021-04-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('choice_id', models.AutoField(primary_key=True, serialize=False, verbose_name='选择id')),
                ('choice_user_id', models.CharField(max_length=100, verbose_name='用户编号')),
                ('choice_area', models.FloatField(verbose_name='种植水稻的土地面积')),
                ('choice_saving', models.FloatField(verbose_name='储蓄金额')),
                ('choice_insurance', models.FloatField(verbose_name='保险金额')),
                ('choice_lost_situation', models.CharField(max_length=20, verbose_name='受灾赔偿情况')),
                ('choice_gain_money', models.FloatField(verbose_name='获得金额')),
                ('choice_reduce_money', models.FloatField(verbose_name='减少金额')),
                ('choice_saving_gain', models.FloatField(verbose_name='本次储蓄本息和')),
                ('choice_final_value', models.FloatField(verbose_name='本次最终价值')),
                ('choice_remain_saving_gain', models.FloatField(verbose_name='上次账户剩余本息和')),
                ('choice_balance', models.FloatField(verbose_name='账户余额')),
                ('choice_total_balance', models.FloatField(verbose_name='账户总余额')),
            ],
        ),
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('uc_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('uc_user_id', models.CharField(max_length=100, verbose_name='用户编号')),
                ('uc_total_money', models.FloatField(verbose_name='愿意投入金额')),
                ('uc_total_saving', models.FloatField(verbose_name='储蓄愿意投入金额')),
                ('uc_total_insurance', models.FloatField(verbose_name='保险愿意投入金额')),
                ('uc_final_choice', models.CharField(max_length=100, verbose_name='用户最终选择')),
            ],
        ),
    ]
