# Generated by Django 3.1.6 on 2021-04-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_userchoice_uc_integral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoice',
            name='uc_final_choice',
            field=models.CharField(blank=True, max_length=100, verbose_name='用户最终选择'),
        ),
        migrations.AlterField(
            model_name='userchoice',
            name='uc_integral',
            field=models.FloatField(blank=True, verbose_name='最终积分'),
        ),
    ]
