# Generated by Django 3.1.6 on 2021-04-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_auto_20210402_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_times',
            field=models.IntegerField(verbose_name='当前实验次数'),
        ),
    ]
