# Generated by Django 3.1.6 on 2021-04-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_auto_20210402_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoice',
            name='uc_final_choice',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用户最终选择'),
        ),
        migrations.AlterField(
            model_name='userchoice',
            name='uc_integral',
            field=models.FloatField(blank=True, null=True, verbose_name='最终积分'),
        ),
    ]
