# Generated by Django 3.1.6 on 2021-04-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0006_auto_20210402_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_is_get',
            field=models.CharField(default='', max_length=10, verbose_name='是否获得赔偿'),
            preserve_default=False,
        ),
    ]
