# Generated by Django 3.1.7 on 2021-04-16 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0008_auto_20210415_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': '实验记录', 'verbose_name_plural': '实验记录'},
        ),
        migrations.AlterModelOptions(
            name='userchoice',
            options={'verbose_name': '所有用户', 'verbose_name_plural': '所有用户'},
        ),
    ]
